---
name: Terraform R2 Run

on: workflow_dispatch

jobs:
  terraform-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

      - uses: tenable/terrascan-action@v1.4.1
        name: Run Terrascan
        id: terrascan
        with:
          iac_type: ${{ vars.IAC_TYPE }}
          iac_version: ${{ IAC_VERSION }}
          policy_type: ${{ POLICY_TYPE }}
          only_warn: true
          scm_token: ${{ secrets.SCM_ACCESS_TOKEN }}
          #verbose: true
          #sarif_upload: true
          #non_recursive:
          #iac_dir:
          #policy_path:
          #skip_rules:
          #config_path:
          #find_vulnerabilities:
          #webhook_url:
          #webhook_token:

      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.1.7

      - id: init
        run: terraform init

      - id: plan
        run: terraform plan -no-color 
        env:
          TF_VAR_CF_R2_ACCESS_KEY_ID: "${{ secrets.CF_R2_ACCESS_KEY_ID }}"
          TF_VAR_CF_R2_SECRET_ACCESS_KEY: "${{ secrets.CF_R2_SECRET_ACCESS_KEY }}"
          TF_VAR_CF_ACCOUNT_ID: "${{ secrets.CF_ACCOUNT_ID }}"
      
      - id: apply
        run: terraform apply --auto-approve 
        env:
          TF_VAR_CF_R2_ACCESS_KEY_ID: "${{ secrets.CF_R2_ACCESS_KEY_ID }}"
          TF_VAR_CF_R2_SECRET_ACCESS_KEY: "${{ secrets.CF_R2_SECRET_ACCESS_KEY }}"
          TF_VAR_CF_ACCOUNT_ID: "${{ secrets.CF_ACCOUNT_ID }}"
